# PostgreSQL. Versions 8.2 and up are supported.
# Use 'createuser -s postgres' to create a general purpose db (super)user.

development: &default
  adapter: postgresql
  encoding: unicode
  database: chatech_jobs_development
  username: postgres
  pool: 5
  timeout: 5000

test:
  <<: *default
  database: chatech_jobs_test
  min_messages: warning

acceptance:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
